name: Publish site

on:
  push:
    tags:
      - '*'
  schedule:
      - cron: "0 18 * * *"

jobs:
  publish-site:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - run: make setup xkcd.ttf help.fr

      - run: make check fetch curfew

      - run: |
             git config user.name coviiid
             git config user.email coviiid@github.users
             mv *.png fig
             git commit -m "add `date +%F` graphs" fig
             git push origin HEAD:master
