name: Publish site

on:
  push:
    tags:
      - '*'
  schedule:
      - cron: "0 18 * * *"

jobs:
  publish-site:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - run: make setup xkcd.ttf help.fr

      - run: make check

      - run: make wait-for-data.csv
      - run: make figures
      - run: make push
